--- #YAML:1.0
name:               MusicBrainz-Collection
version:            0.01
abstract:           Upload album collection list to MusicBrainz
author:
    - Andy Grundman <andy@hybridized.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Audio::Scan:     0.58
    File::Next:      0
    LWP::UserAgent:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
